//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammingTask1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CffKeywords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CffKeywords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgrammingTask1.CffKeywords", typeof(CffKeywords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0.
        /// </summary>
        internal static string C0 {
            get {
                return ResourceManager.GetString("C0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C1.
        /// </summary>
        internal static string C1 {
            get {
                return ResourceManager.GetString("C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2.
        /// </summary>
        internal static string C2 {
            get {
                return ResourceManager.GetString("C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEFAULT.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD.
        /// </summary>
        internal static string DownSpeed {
            get {
                return ResourceManager.GetString("DownSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-TASKS.
        /// </summary>
        internal static string EndAllTasks {
            get {
                return ResourceManager.GetString("EndAllTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-LIMITS.
        /// </summary>
        internal static string EndLimits {
            get {
                return ResourceManager.GetString("EndLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-LOCAL-COMMUNICATION.
        /// </summary>
        internal static string EndLocalCommunication {
            get {
                return ResourceManager.GetString("EndLocalCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-LOGFILE.
        /// </summary>
        internal static string EndLogfile {
            get {
                return ResourceManager.GetString("EndLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-PROCESSOR.
        /// </summary>
        internal static string EndProcessor {
            get {
                return ResourceManager.GetString("EndProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-PROCESSORS.
        /// </summary>
        internal static string EndProcessors {
            get {
                return ResourceManager.GetString("EndProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-PROCESSOR-TYPE.
        /// </summary>
        internal static string EndProcessorType {
            get {
                return ResourceManager.GetString("EndProcessorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-PROCESSOR-TYPES.
        /// </summary>
        internal static string EndProcessorTypes {
            get {
                return ResourceManager.GetString("EndProcessorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-PROGRAM.
        /// </summary>
        internal static string EndProgram {
            get {
                return ResourceManager.GetString("EndProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-REMOTE-COMMUNICATION.
        /// </summary>
        internal static string EndRemoteCommunication {
            get {
                return ResourceManager.GetString("EndRemoteCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END-TASK.
        /// </summary>
        internal static string EndSingleTask {
            get {
                return ResourceManager.GetString("EndSingleTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREQUENCY.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIMITS.
        /// </summary>
        internal static string Limits {
            get {
                return ResourceManager.GetString("Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL-COMMUNICATION.
        /// </summary>
        internal static string LocalCommunication {
            get {
                return ResourceManager.GetString("LocalCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGFILE.
        /// </summary>
        internal static string Logfile {
            get {
                return ResourceManager.GetString("Logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-DOWNLOAD.
        /// </summary>
        internal static string MaxDownSpeed {
            get {
                return ResourceManager.GetString("MaxDownSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-PROCESSOR-FREQUENCIES.
        /// </summary>
        internal static string MaxProcessorFreq {
            get {
                return ResourceManager.GetString("MaxProcessorFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-PROCESSORS.
        /// </summary>
        internal static string MaxProcessors {
            get {
                return ResourceManager.GetString("MaxProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-RAM.
        /// </summary>
        internal static string MaxRam {
            get {
                return ResourceManager.GetString("MaxRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-TASKS.
        /// </summary>
        internal static string MaxTasks {
            get {
                return ResourceManager.GetString("MaxTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM-UPLOAD.
        /// </summary>
        internal static string MaxUpSpeed {
            get {
                return ResourceManager.GetString("MaxUpSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-DOWNLOAD.
        /// </summary>
        internal static string MinDownSpeed {
            get {
                return ResourceManager.GetString("MinDownSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-PROCESSOR-FREQUENCIES.
        /// </summary>
        internal static string MinProcessorFreq {
            get {
                return ResourceManager.GetString("MinProcessorFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-PROCESSORS.
        /// </summary>
        internal static string MinProcessors {
            get {
                return ResourceManager.GetString("MinProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-RAM.
        /// </summary>
        internal static string MinRam {
            get {
                return ResourceManager.GetString("MinRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-TASKS.
        /// </summary>
        internal static string MinTasks {
            get {
                return ResourceManager.GetString("MinTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM-UPLOAD.
        /// </summary>
        internal static string MinUpSpeed {
            get {
                return ResourceManager.GetString("MinUpSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSOR.
        /// </summary>
        internal static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSORS.
        /// </summary>
        internal static string Processors {
            get {
                return ResourceManager.GetString("Processors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSOR-TYPE.
        /// </summary>
        internal static string ProcessorType {
            get {
                return ResourceManager.GetString("ProcessorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSOR-TYPES.
        /// </summary>
        internal static string ProcessorTypes {
            get {
                return ResourceManager.GetString("ProcessorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROGRAM.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DURATION.
        /// </summary>
        internal static string ProgramDuration {
            get {
                return ResourceManager.GetString("ProgramDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSORS.
        /// </summary>
        internal static string ProgramProcessors {
            get {
                return ResourceManager.GetString("ProgramProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASKS.
        /// </summary>
        internal static string ProgramTasks {
            get {
                return ResourceManager.GetString("ProgramTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        internal static string Ram {
            get {
                return ResourceManager.GetString("Ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFERENCE-FREQUENCY.
        /// </summary>
        internal static string ReferenceFreq {
            get {
                return ResourceManager.GetString("ReferenceFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOTE-COMMUNICATION.
        /// </summary>
        internal static string RemoteCommunication {
            get {
                return ResourceManager.GetString("RemoteCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUNTIME.
        /// </summary>
        internal static string Runtime {
            get {
                return ResourceManager.GetString("Runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASK.
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TASKS.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD.
        /// </summary>
        internal static string UpSpeed {
            get {
                return ResourceManager.GetString("UpSpeed", resourceCulture);
            }
        }
    }
}
